POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Rest adds note",
  "important": false
}

###
POST http://localhost:3001/api/notes/1
Content-Type: application/json

{
  "id": "1",
  "content": "Rest adds note",
  "important": false
}

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/2

###
DELETE  http://localhost:3001/api/notes/2